#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD_DIR="$ROOT_DIR/build"
GENERATED_DIR="$ROOT_DIR/src/generated"
VERSION_FILE="$ROOT_DIR/VERSION"
VERSION="$(tr -d '[:space:]' < "$VERSION_FILE")"
DISPLAY_VERSION="${VERSION%%-*}"
OUTPUT_BIN="$BUILD_DIR/pac48.bin"
OUTPUT_TAP="$BUILD_DIR/pac48.tap"
VERSIONED_TAP="$BUILD_DIR/pac48-${VERSION}.tap"
GENERATED_SPRITES="$GENERATED_DIR/pac_shifted.asm"
GENERATED_BUILD_INFO="$GENERATED_DIR/build_info.asm"
TAP_LOAD_SNAPSHOT="$BUILD_DIR/tap_load.z80"
TAP_LOAD_LOG="$BUILD_DIR/tap_load.log"
MAX_BIN_BYTES=28672

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    echo "Error: required command '$1' not found." >&2
    exit 1
  }
}

require_cmd python3
require_cmd sjasmplus
require_cmd bin2tap.py
require_cmd tap2sna.py
require_cmd trace.py
require_cmd snapinfo.py
test -n "$VERSION" || { echo "ERROR: VERSION file is empty"; exit 1; }

mkdir -p "$BUILD_DIR" "$GENERATED_DIR"
cd "$ROOT_DIR"

# Build identity is part of the binary UI and release filename. CI builds use
# the exact clean commit SHA. Local dirty builds are prefixed with D so a
# screenshot can never be mistaken for a clean release build.
if [[ -n "${PAC48_BUILD_ID:-}" ]]; then
  BUILD_ID="$(printf '%s' "$PAC48_BUILD_ID" | tr '[:lower:]' '[:upper:]')"
elif command -v git >/dev/null 2>&1 && git -C "$ROOT_DIR" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  FULL_SHA="$(git -C "$ROOT_DIR" rev-parse HEAD)"
  BUILD_ID="$(printf '%s' "${FULL_SHA:0:7}" | tr '[:lower:]' '[:upper:]')"
  if ! git -C "$ROOT_DIR" diff --quiet --ignore-submodules -- || \
     ! git -C "$ROOT_DIR" diff --cached --quiet --ignore-submodules --; then
    BUILD_ID="D${BUILD_ID:0:6}"
  fi
else
  BUILD_ID="0000000"
fi

if [[ ! "$BUILD_ID" =~ ^[0-9A-F]{7}$ && ! "$BUILD_ID" =~ ^D[0-9A-F]{6}$ ]]; then
  echo "ERROR: build id '$BUILD_ID' must be 7 hex chars or D + 6 hex chars" >&2
  exit 1
fi

SCREEN_LABEL="V${DISPLAY_VERSION} B${BUILD_ID}"
LABEL_WIDTH=$(( ${#SCREEN_LABEL} * 4 - 1 ))
LABEL_X=$(( (256 - LABEL_WIDTH) / 2 ))
BUILD_SPECIFIC_TAP="$BUILD_DIR/pac48-${VERSION}-b${BUILD_ID}.tap"

printf '%s\n' "$BUILD_ID" > "$BUILD_DIR/build_id.txt"
printf '%s\n' "$SCREEN_LABEL" > "$BUILD_DIR/screen_label.txt"

cat > "$GENERATED_BUILD_INFO" <<EOF
; AUTO-GENERATED by tools/build.sh. Do not edit.
; VERSION is the canonical version source; BUILD_ID comes from the Git commit.
Build_MenuTitle:
    DB "PAC48 ${VERSION}",13,0

Build_ScreenLabel:
    DB "${SCREEN_LABEL}",0

Build_ScreenLabelX     EQU ${LABEL_X}
Build_ScreenLabelWidth EQU ${LABEL_WIDTH}

Build_VersionText:
    DB "${VERSION}",0
Build_IdText:
    DB "${BUILD_ID}",0
EOF

echo "[1/9] Generating build metadata and masked pre-shifted sprites..."
echo "  Version: $VERSION"
echo "  Build ID: $BUILD_ID"
echo "  Screen stamp: $SCREEN_LABEL"
python3 tools/gen_shifted_sprites.py src/sprites.asm "$GENERATED_SPRITES"

echo "[2/9] Running structural, architecture and build-identity checks..."
python3 tools/check_project.py \
  --maze src/maze.asm \
  --generated-sprites "$GENERATED_SPRITES" \
  --source-root src
python3 tools/check_build_identity.py \
  --version VERSION \
  --build-info "$GENERATED_BUILD_INFO" \
  --main src/main.asm \
  --menu src/menu.asm

echo "[3/9] Running renderer reference-model tests..."
python3 tools/test_render_model.py

echo "[4/9] Assembling game..."
sjasmplus --raw="$OUTPUT_BIN" src/main.asm
test -f "$OUTPUT_BIN" || { echo "ERROR: sjasmplus did not create $OUTPUT_BIN"; exit 1; }

python3 tools/check_project.py \
  --maze src/maze.asm \
  --generated-sprites "$GENERATED_SPRITES" \
  --source-root src \
  --binary "$OUTPUT_BIN" \
  --max-binary-bytes "$MAX_BIN_BYTES"

echo "[5/9] Running headless Z80 runtime harness..."
chmod +x tools/run_runtime_tests.sh
tools/run_runtime_tests.sh

echo "[6/9] Measuring Render_Commit with 48K contention..."
chmod +x tools/run_perf_tests.sh
tools/run_perf_tests.sh

echo "[7/9] Creating TAP files..."
bin2tap.py -o 32768 -s 32768 -c 32767 "$OUTPUT_BIN" "$OUTPUT_TAP"
cp "$OUTPUT_TAP" "$VERSIONED_TAP"
cp "$OUTPUT_TAP" "$BUILD_SPECIFIC_TAP"

echo "[8/9] Verifying version/build-specific outputs..."
test -s "$VERSIONED_TAP"
test -s "$BUILD_SPECIFIC_TAP"
test -s "$GENERATED_BUILD_INFO"

echo "[9/9] Simulating a fresh 48K TAP load to entry point..."
rm -f "$TAP_LOAD_SNAPSHOT" "$TAP_LOAD_LOG"
if ! tap2sna.py --start 32768 "$OUTPUT_TAP" "$TAP_LOAD_SNAPSHOT" >"$TAP_LOAD_LOG" 2>&1; then
  echo "ERROR: simulated 48K TAP load failed" >&2
  cat "$TAP_LOAD_LOG" >&2 || true
  exit 1
fi
test -s "$TAP_LOAD_SNAPSHOT" || {
  echo "ERROR: tap2sna.py did not create $TAP_LOAD_SNAPSHOT" >&2
  exit 1
}

snapinfo.py "$TAP_LOAD_SNAPSHOT" >>"$TAP_LOAD_LOG"
grep -Eq '(^|[^0-9])32768([^0-9]|$)|\$8000|0x8000' "$TAP_LOAD_LOG" || {
  echo "ERROR: TAP load snapshot evidence does not show entry PC 32768/$8000" >&2
  cat "$TAP_LOAD_LOG" >&2 || true
  exit 1
}

BIN_BYTES="$(wc -c < "$OUTPUT_BIN" | tr -d '[:space:]')"
HEADROOM_BYTES="$((MAX_BIN_BYTES - BIN_BYTES))"

echo
echo "Build complete:"
echo "  Version: $VERSION"
echo "  Build ID: $BUILD_ID"
echo "  Screen stamp: $SCREEN_LABEL"
echo "  BIN: $OUTPUT_BIN ($BIN_BYTES bytes)"
echo "  Upper-RAM budget headroom: $HEADROOM_BYTES bytes before safety ceiling"
echo "  TAP: $OUTPUT_TAP"
echo "  Versioned TAP: $VERSIONED_TAP"
echo "  Build-specific TAP: $BUILD_SPECIFIC_TAP"
echo "  TAP load simulation: PASS (fresh 48K -> entry 32768)"
echo "  Generated sprites: $GENERATED_SPRITES"
echo "  Generated build info: $GENERATED_BUILD_INFO"
if [[ -s "$BUILD_DIR/perf_results.txt" ]]; then
  echo "  Render_Commit T-states:"
  sed 's/^/    /' "$BUILD_DIR/perf_results.txt"
fi
