#!/usr/bin/env python3
"""Deterministic structural and architecture checks for PAC48.

These checks are intentionally emulator-independent. They catch repository,
asset, and known-architecture regressions before assembly/runtime verification.
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

MAZE_WIDTH = 28
MAZE_HEIGHT = 20
EXPECTED_MAZE_CELLS = MAZE_WIDTH * MAZE_HEIGHT
EXPECTED_SHIFTED_SPRITES = 4 * 5 * 8

PHASE_LABEL_RE = re.compile(
    r"^(Pac_Shifted_(Right|Left|Up|Down)_F([0-4])_P([0-7])):$",
    flags=re.MULTILINE,
)
BINARY_BYTE_RE = re.compile(r"^%[01]{8}$")


def fail(message: str) -> None:
    raise ValueError(message)


def parse_defb_values(payload: str) -> list[int]:
    values: list[int] = []
    for token in payload.split(","):
        token = token.strip()
        if token:
            values.append(int(token, 0))
    return values


def check_maze(path: pathlib.Path) -> None:
    text = path.read_text(encoding="utf-8")
    marker = "Maze_Map:"
    if marker not in text:
        fail(f"{path}: missing {marker}")

    tail = text.split(marker, 1)[1]
    rows: list[list[int]] = []
    for line in tail.splitlines():
        code = line.split(";", 1)[0].strip()
        if not code.upper().startswith("DEFB"):
            continue
        rows.append(parse_defb_values(code[4:].strip()))

    if len(rows) != MAZE_HEIGHT:
        fail(f"{path}: Maze_Map has {len(rows)} DEFB rows; expected {MAZE_HEIGHT}")

    bad_widths = [(index, len(row)) for index, row in enumerate(rows) if len(row) != MAZE_WIDTH]
    if bad_widths:
        details = ", ".join(f"row {index}={width}" for index, width in bad_widths)
        fail(f"{path}: maze row widths invalid ({details}); expected {MAZE_WIDTH} each")

    values = [value for row in rows for value in row]
    if len(values) != EXPECTED_MAZE_CELLS:
        fail(
            f"{path}: Maze_Map has {len(values)} cells; "
            f"expected {EXPECTED_MAZE_CELLS} ({MAZE_WIDTH}x{MAZE_HEIGHT})"
        )

    invalid = sorted(set(values) - {0, 1, 2})
    if invalid:
        fail(f"{path}: unexpected maze cell values: {invalid}")


def check_phase_block(path: pathlib.Path, label: str, block: str) -> None:
    rows: list[list[str]] = []
    for line in block.splitlines():
        code = line.split(";", 1)[0].strip()
        if not code:
            continue
        if code.endswith(":") or code.upper().startswith("DW"):
            break
        if code.upper().startswith("DEFB"):
            rows.append([token.strip() for token in code[4:].strip().split(",") if token.strip()])

    if len(rows) != 8:
        fail(f"{path}: {label} has {len(rows)} scanlines; expected 8")

    for row_index, row in enumerate(rows):
        if len(row) != 4:
            fail(
                f"{path}: {label} row {row_index} has {len(row)} bytes; "
                "expected maskL,imageL,maskR,imageR"
            )
        invalid = [token for token in row if not BINARY_BYTE_RE.match(token)]
        if invalid:
            fail(f"{path}: {label} row {row_index} has invalid generated bytes: {invalid}")


def check_pointer_table(path: pathlib.Path, text: str, direction: str) -> None:
    marker = f"Pac_ShiftedTable{direction}:"
    if marker not in text:
        fail(f"{path}: missing pointer table {marker}")

    section = text.split(marker, 1)[1]
    refs: list[str] = []
    dw_lines = 0
    for line in section.splitlines():
        code = line.split(";", 1)[0].strip()
        if not code:
            if dw_lines:
                break
            continue
        if not code.upper().startswith("DW"):
            if dw_lines:
                break
            continue
        dw_lines += 1
        refs.extend(token.strip() for token in code[2:].strip().split(",") if token.strip())

    if dw_lines != 5:
        fail(f"{path}: {marker} has {dw_lines} DW rows; expected 5")
    if len(refs) != 40:
        fail(f"{path}: {marker} has {len(refs)} pointers; expected 40")

    expected = {
        f"Pac_Shifted_{direction}_F{frame}_P{phase}"
        for frame in range(5)
        for phase in range(8)
    }
    if set(refs) != expected or len(set(refs)) != 40:
        fail(f"{path}: {marker} does not contain exactly one pointer to every frame/phase")


def check_generated_sprites(path: pathlib.Path) -> None:
    text = path.read_text(encoding="utf-8")
    matches = list(PHASE_LABEL_RE.finditer(text))
    labels = [match.group(1) for match in matches]

    if len(labels) != EXPECTED_SHIFTED_SPRITES:
        fail(
            f"{path}: found {len(labels)} shifted sprite phases; "
            f"expected {EXPECTED_SHIFTED_SPRITES}"
        )
    if len(set(labels)) != EXPECTED_SHIFTED_SPRITES:
        fail(f"{path}: generated sprite phase labels are not unique")

    for index, match in enumerate(matches):
        start = match.end()
        end = matches[index + 1].start() if index + 1 < len(matches) else len(text)
        check_phase_block(path, match.group(1), text[start:end])

    for direction in ("Right", "Left", "Up", "Down"):
        check_pointer_table(path, text, direction)


def code_without_comments(text: str) -> str:
    return "\n".join(line.split(";", 1)[0] for line in text.splitlines())


def check_architecture(source_root: pathlib.Path) -> None:
    main_path = source_root / "main.asm"
    video_path = source_root / "video.asm"
    player_path = source_root / "player.asm"
    sprites_path = source_root / "sprites.asm"
    render_path = source_root / "render.asm"

    main = code_without_comments(main_path.read_text(encoding="utf-8"))
    video = code_without_comments(video_path.read_text(encoding="utf-8"))
    player = code_without_comments(player_path.read_text(encoding="utf-8"))
    sprites = code_without_comments(sprites_path.read_text(encoding="utf-8"))
    render = code_without_comments(render_path.read_text(encoding="utf-8"))

    if "MainLoop:" not in main:
        fail(f"{main_path}: missing MainLoop label")
    main_loop = main.split("MainLoop:", 1)[1]
    if re.search(r"\bCALL\s+Maze_Draw\b", main_loop, flags=re.IGNORECASE):
        fail(f"{main_path}: INC-2026-003 regression: Maze_Draw returned to MainLoop")
    if not re.search(r"\bCALL\s+Render_Commit\b", main_loop, flags=re.IGNORECASE):
        fail(f"{main_path}: MainLoop must call Render_Commit")
    if not re.search(r"\bCALL\s+Render_Prepare\b", main_loop, flags=re.IGNORECASE):
        fail(f"{main_path}: MainLoop must call Render_Prepare")

    if re.search(r"^Video_DrawSpritePx:", video, flags=re.MULTILINE | re.IGNORECASE):
        fail(f"{video_path}: INC-2026-003 regression: runtime-shift Video_DrawSpritePx restored")

    forbidden_player_patterns = (
        r"\bSCREEN_ADDR\b",
        r"\bATTR_ADDR\b",
        r"\bCALL\s+Video_",
        r"\bCALL\s+Render_",
        r"^Player_Draw:",
    )
    for pattern in forbidden_player_patterns:
        if re.search(pattern, player, flags=re.MULTILINE | re.IGNORECASE):
            fail(f"{player_path}: player simulation regained direct screen/render ownership ({pattern})")

    if re.search(r"^Pac_FrameTable(?:Right|Left|Up|Down):", sprites, flags=re.MULTILINE):
        fail(f"{sprites_path}: obsolete hand-written mobile actor pointer tables restored")

    if "Render_DrawMasked8x8:" not in render:
        fail(f"{render_path}: missing masked actor renderer")
    if re.search(r"\bCALL\s+Input_Read\b", render, flags=re.IGNORECASE):
        fail(f"{render_path}: renderer must not own physical/logical input polling")

    # Dirty background restoration must not duplicate an attribute-only pass
    # immediately before the bitmap+attribute cell draw.
    maze_text = code_without_comments((source_root / "maze.asm").read_text(encoding="utf-8"))
    if "Maze_DrawCell:" not in maze_text or "Maze_CanMove:" not in maze_text:
        fail(f"{source_root / 'maze.asm'}: expected Maze_DrawCell/Maze_CanMove boundaries missing")
    draw_cell = maze_text.split("Maze_DrawCell:", 1)[1].split("Maze_CanMove:", 1)[0]
    if re.search(r"\bCALL\s+Maze_DrawTileAtOffset\b", draw_cell, flags=re.IGNORECASE):
        fail(
            f"{source_root / 'maze.asm'}: dirty restore reintroduced redundant attribute-only write"
        )


def check_binary(path: pathlib.Path, max_bytes: int) -> None:
    size = path.stat().st_size
    if size <= 0:
        fail(f"{path}: binary is empty")
    if size > max_bytes:
        fail(
            f"{path}: binary is {size} bytes; safe budget is {max_bytes} bytes "
            "from ORG 32768, reserving upper-RAM stack/headroom"
        )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--maze", type=pathlib.Path, required=True)
    parser.add_argument("--generated-sprites", type=pathlib.Path, required=True)
    parser.add_argument("--source-root", type=pathlib.Path, required=True)
    parser.add_argument("--binary", type=pathlib.Path)
    parser.add_argument("--max-binary-bytes", type=int, default=28672)
    args = parser.parse_args()

    try:
        check_maze(args.maze)
        check_generated_sprites(args.generated_sprites)
        check_architecture(args.source_root)
        if args.binary is not None:
            check_binary(args.binary, args.max_binary_bytes)
    except (OSError, ValueError) as exc:
        print(f"project check failed: {exc}", file=sys.stderr)
        return 1

    print("PAC48 structural and architecture checks passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
