; =========================
; CONFIG / COSTANTI GLOBALI
; =========================

PORT_ULA        EQU 254
PORT_KEMPSTON  EQU 31

SCREEN_ADDR    EQU 16384
ATTR_ADDR      EQU 22528

COLOR_BLACK    EQU 0
COLOR_BLUE     EQU 1
COLOR_RED      EQU 2
COLOR_MAGENTA  EQU 3
COLOR_GREEN    EQU 4
COLOR_CYAN     EQU 5
COLOR_YELLOW   EQU 6
COLOR_WHITE    EQU 7
