; ==========================================
; PAC48 - hud.asm
; Tiny startup-only build/version stamp
; ==========================================
;
; Draws Build_ScreenLabel (generated by tools/build.sh) in the free top screen
; band. The maze starts at pixel y=16, so this 3x5 font never overlaps gameplay.
; The stamp is intentionally rendered once after Video_Clear/Video_InitLineTable
; and is not part of the hot frame path.

HUD_Attr       EQU 64 | COLOR_WHITE      ; BRIGHT white INK on black PAPER
HUD_LabelY     EQU 1

HUD_CursorX:   DB 0

; Draw the generated label, e.g. "V0.3.5 B1A2B3C", centered at the top.
HUD_DrawBuildStamp:
    ; Give the complete top attribute row a stable white-on-black palette.
    LD HL, ATTR_ADDR
    LD DE, ATTR_ADDR + 1
    LD BC, 31
    LD A, HUD_Attr
    LD (HL), A
    LDIR

    LD A, Build_ScreenLabelX
    LD (HUD_CursorX), A
    LD HL, Build_ScreenLabel
.next_char:
    LD A, (HL)
    OR A
    RET Z
    PUSH HL
    CALL HUD_GetGlyph
    CALL HUD_DrawGlyph3x5
    POP HL
    INC HL
    JR .next_char

; In: A=ASCII character
; Out: HL=pointer to five 3-bit rows.
; Supported: 0-9, A-F, V, '.', space. Unknown characters render blank.
HUD_GetGlyph:
    CP 48                          ; '0'
    JR C, .letters
    CP 58                          ; after '9'
    JR NC, .letters
    SUB 48
    JR .index

.letters:
    CP 65                          ; 'A'
    JR C, .special
    CP 71                          ; after 'F'
    JR NC, .special
    SUB 65
    ADD A, 10
    JR .index

.special:
    CP 86                          ; 'V'
    JR Z, .v
    CP 46                          ; '.'
    JR Z, .dot
    LD A, 18                      ; blank / space / unsupported
    JR .index
.v:
    LD A, 16
    JR .index
.dot:
    LD A, 17

.index:
    ; Each glyph occupies 5 bytes: offset = index * 5.
    LD E, A
    LD D, 0
    LD L, A
    LD H, 0
    ADD HL, HL                    ; *2
    ADD HL, HL                    ; *4
    ADD HL, DE                    ; *5
    LD DE, HUD_Glyphs
    ADD HL, DE
    RET

; In: HL=five glyph rows. Uses HUD_CursorX, advances it by 4 pixels.
HUD_DrawGlyph3x5:
    LD B, 5
    LD E, HUD_LabelY
.row:
    LD C, (HL)
    INC HL
    LD A, (HUD_CursorX)
    LD D, A

    BIT 2, C
    CALL NZ, HUD_DrawPixel
    INC D
    BIT 1, C
    CALL NZ, HUD_DrawPixel
    INC D
    BIT 0, C
    CALL NZ, HUD_DrawPixel

    INC E
    DJNZ .row

    LD A, (HUD_CursorX)
    ADD A, 4                      ; 3 pixels + 1 pixel spacing
    LD (HUD_CursorX), A
    RET

; In: D=x pixel 0..255, E=y pixel 0..191
; Sets one bitmap pixel. Preserves AF/BC/DE.
HUD_DrawPixel:
    PUSH AF
    PUSH BC
    PUSH DE

    LD A, E
    CALL Video_GetLineAddress

    LD A, D
    SRL A
    SRL A
    SRL A
    LD C, A
    LD B, 0
    ADD HL, BC

    LD A, D
    AND 7
    LD B, A
    LD A, $80
    JR Z, .mask_ready
.shift_mask:
    RRCA
    DJNZ .shift_mask
.mask_ready:
    OR (HL)
    LD (HL), A

    POP DE
    POP BC
    POP AF
    RET

; 3x5 glyphs. Bits 2..0 are left..right.
; 0-9
HUD_Glyphs:
    DEFB %111,%101,%101,%101,%111    ; 0
    DEFB %010,%110,%010,%010,%111    ; 1
    DEFB %111,%001,%111,%100,%111    ; 2
    DEFB %111,%001,%111,%001,%111    ; 3
    DEFB %101,%101,%111,%001,%001    ; 4
    DEFB %111,%100,%111,%001,%111    ; 5
    DEFB %111,%100,%111,%101,%111    ; 6
    DEFB %111,%001,%010,%010,%010    ; 7
    DEFB %111,%101,%111,%101,%111    ; 8
    DEFB %111,%101,%111,%001,%111    ; 9

    ; A-F (build SHA may contain hexadecimal letters)
    DEFB %010,%101,%111,%101,%101    ; A
    DEFB %110,%101,%110,%101,%110    ; B
    DEFB %111,%100,%100,%100,%111    ; C
    DEFB %110,%101,%101,%101,%110    ; D
    DEFB %111,%100,%110,%100,%111    ; E
    DEFB %111,%100,%110,%100,%100    ; F

    DEFB %101,%101,%101,%101,%010    ; V
    DEFB %000,%000,%000,%000,%010    ; .
    DEFB %000,%000,%000,%000,%000    ; blank
